Enhancement/cleanup
wistcc/werewolf-brain pull request #20
Opened 2016-12-31 20:16 UTC by wOvalle

2016-12-31 21:02 UTC, wistcc requested changes

2016-12-31 21:02 UTC, wistcc commented on index.js
> +        negatives: cards.filter(c => c.value < 0),
This won't work. Let's say for example we receive this:

```
[
     { role: 'Villager', value: 1, amount: 4 }, 
     { role: 'Werewolf', value: -6 amount: 1 }
]
```

In order to balance the game we need to have all cards individually like this:

```
[
     { role: 'Villager', value: 1, amount: 1 }, 
     { role: 'Villager', value: 1, amount: 1 }, 
     { role: 'Villager', value: 1, amount: 1 }, 
     { role: 'Villager', value: 1, amount: 1 }, 
     { role: 'Werewolf', value: -6 amount: 1 }
]
```

Here we do that process:
```
cards.map(function (card) {
         if (card.value < 0)		
             for (var i = 0; i < card.amount; i++)		
                 deck.negatives.push({ role: card.role, value: card.value, amount: 1 });		
         else		
             for (var i = 0; i < card.amount; i++)		
                 deck.nonnegatives.push({ role: card.role, value: card.value, amount: 1 });		
     });
```

2016-12-31 22:04 UTC, vetom commented on index.js
> +function _getChaosGame(players, chosenCards = cards.getAll()) {
Clever one!

2017-01-02 01:42 UTC, wOvalle commented
@wistcc made the requested changes!

2017-01-02 12:08 UTC, wistcc approved these changes

2017-01-02 12:08 UTC, vetom approved these changes

2017-01-02 12:08 UTC, merged