Feature/scripts
wistcc/werewolf-brain pull request #23
Opened 2017-01-04 03:47 UTC by vetom

This closes #18.

2017-01-04 03:54 UTC, vetom commented
Script diagram updated.
![roles](https://cloud.githubusercontent.com/assets/6082977/21631295/e99bf72c-d20f-11e6-9203-a3ac5d6e83a2.JPG)

2017-01-04 04:00 UTC, vetom commented
In the script, the asterisks symbol ( * ) means first night call only.

2017-01-04 13:23 UTC, wistcc requested changes

2017-01-04 13:23 UTC, wistcc commented on index.js
> +exports.getGameScript = function (game) {
This function is not necessary. If I a have a game object I just need to pass `game.Deck` to the `getScriptFromDeck` function!

2017-01-04 13:23 UTC, wistcc commented on moderator.js
> +exports.getScriptFromGame = function (game) {
This function is not necessary. If I a have a game object I just need to pass `game.Deck` to the `getScriptFromDeck` function!

2017-01-04 13:34 UTC, wistcc commented on moderator.js
> +    if(deck['Lycan']) script += ' - ' + lang.english['Lycan'] + '\n';
[Single comment, not necessary to approve the PR] I think we should have another logic to do this, I suggest the next:
- Receive a string with the selected language.
- The `selectedLang` array should be sorted.
- Loop through the `selectedLang` array and do the check.

If we have a logic like this, we got some benefits:
- When we add other languages, we already have the logic to support them.
- DRY. We don't need to have so many `if` statements.
- DRY. We don't have to repeat this `' - '` and this `'\n'`.
- In order to add roles that are not in the deck, we could add some logic inside the loop to do this very easily.

2017-01-04 13:35 UTC, wistcc requested changes

2017-01-04 13:35 UTC, wistcc commented on moderator.js
> +        script += ' - ' + lang.english['Cupid'] + '\n';
We should merge these two because the are always called just once and one after the other.

2017-01-04 20:29 UTC, vetom commented on languages.js
> +exports.english = {
I will rename this to 'default'

2017-01-05 00:48 UTC, wovalle requested changes

2017-01-05 00:48 UTC, wovalle commented on index.js
> +exports.getGameScript = function (game) {
Ir if it needed, we can do: `exports.getGameScript = moderator.getScriptFromDeck` without the invocation.

2017-01-05 00:48 UTC, wovalle commented on moderator.js
> +    if(deck['Lycan']) script += ' - ' + lang.english['Lycan'] + '\n';
I agree with you Winner. But I would prefer to make an issue with this, internationalization is apart from scripting. 

Also, too many `script += ' - ' + whatever + '\n'`. I would do a function called `addToScript` (or something alike) and add the logic there.

2017-01-05 00:48 UTC, wOvalle commented on languages.js
> +exports.english = {
I wouldn't rename it to default. This is the language pack in english. I would add that `logic` in the languageChooser (or whatever is named).

2017-01-05 00:48 UTC, wOvalle commented on moderator.js
> +        script += ' - ' + lang.english['Cupid'] + '\n';
Agree.

2017-01-05 04:00 UTC, vetom commented on languages.js
> +exports.english = {
I thought to change it to default it's a good idea because we may have several English packs.

2017-01-06 00:44 UTC, vetom commented on cards.js
>      { role: 'Werewolf', value: -6, amount: 12 },
I will order the cards alphabetically. I got some bad time verifying roles.

2017-01-06 00:48 UTC, vetom commented on languages.js
> +exports.english = {
Also, I will order these alphabetically.

2017-01-10 04:11 UTC, wistcc commented
@vetom Looks very good to me, just 2 things:
- Remember to add the `getTemplates` function.
- I would extract to other files the `bindings` and `sequence` objects

2017-01-10 04:11 UTC, wistcc approved these changes

2017-01-10 16:04 UTC, vetom commented
@wistcc The templates function will be introduced in #28

2017-01-11 03:29 UTC, wovalle requested changes

2017-01-11 03:29 UTC, wovalle commented on moderator.js
> +exports.getScriptFromDeck = function (deck) {
[Just a question] If you're exporting a private function, why not export the original function?

```javascript
exports.getScriptFromDeck = function (deck)  {
    var script = '';
    var calls = new Set();
    Object.keys(deck).forEach(function(role) {
        if(bindings[role]) bindings[role].forEach(function (call) {
            calls.add(call);
        });
    });
    secuence.forEach(function (call){
        if(calls.has(call)){
            script += '- ' + lang.default[call] + '\n';
        }
    });
    return script;
}
```

2017-01-11 03:29 UTC, wOvalle commented on moderator.js
> +exports.getScriptFromDeck = function (deck) {
If you're exporting the private function, why not make it public from the beginning?

2017-01-11 03:29 UTC, wOvalle commented on templates.js
> +        'Tanner',
Tanner is a vampire role? wtf? :joy:

2017-01-11 03:29 UTC, wOvalle commented on index.js
> +exports.getScriptFromDeck = function (deck) {
If you're exporting the private function, why not make it public from the beginning?

2017-01-11 03:31 UTC, vetom commented on templates.js
> +        'Tanner',
Not a vampire role! it's part of a vampires game 😂

2017-01-11 03:32 UTC, vetom commented on index.js
> +exports.getScriptFromDeck = function (deck) {
How can I do that❔

2017-01-11 03:36 UTC, wovalle requested changes

2017-01-11 03:36 UTC, wOvalle commented on moderator.js
> +exports.getScriptFromDeck = function (deck) {
```javascript
// Pass the reference 
exports.getScriptFromDeck = _getScriptFromDeck;

// Or simply
exports.getScriptFromDeck (deck) => {
     var script = '';
     var calls = new Set();
     Object.keys(deck).forEach(function(role) {
         if(bindings[role]) bindings[role].forEach(function (call) {
             calls.add(call);
         });
     });
     secuence.forEach(function (call){
         if(calls.has(call)){
             script += '- ' + lang.default[call] + '\n';
         }
     });
     return script;
 } 


```

2017-01-11 04:02 UTC, wovalle approved these changes

2017-01-11 04:09 UTC, merged