Updating tests
wistcc/werewolf-brain pull request #46
Opened 2017-02-07 06:49 UTC by vetom

Addressing feedbacks from #45, this closes #44.

2017-02-08 20:21 UTC, wistcc requested changes

2017-02-08 20:21 UTC, wistcc commented on tests/game.js
> -    const players = getRandom(5, 18);
You should remove the `getRandom` function!

2017-02-09 02:37 UTC, wovalle approved these changes

2017-02-09 03:12 UTC, wistcc approved these changes

2017-02-09 03:12 UTC, merged